language: generic
os: linux
dist: xenial

services:
  - docker

jobs:
  include:
    - &android
      compiler: clang
      script: |
        docker run -it -v ${TRAVIS_BUILD_DIR}:/source bojoe/cpp-android-ndk-build-env-ubuntu:r22beta1 '
        id
        cmake -H/source -B/home/developer/build -GNinja -DCMAKE_TOOLCHAIN_FILE=/opt/androidSdk/ndk/android-ndk-r22-beta1/build/cmake/android.toolchain.cmake -DANDROID_ABI=${ANDROID_ABI} -DANDROID_PLATFORM=${ANDROID_PLATFORM} -DCMAKE_BUILD_TYPE=Release -DPEGTL_BUILD_EXAMPLES=OFF
        cmake --build /home/developer/build --target all | cat -'
      env:
        - ANDROID_ABI=armeabi-v7a
        - ANDROID_PLATFORM=android-26

    - <<: *android
      env:
        - ANDROID_ABI=arm64-v8a
        - ANDROID_PLATFORM=android-26
