language: generic
os: linux
dist: xenial

services:
  - docker

jobs:
  include:
    - &android
      compiler: clang
      script: |
        docker run -it -v ${TRAVIS_BUILD_DIR}:/source bojoe/cpp-android-ndk-build-env-ubuntu:r22beta1 '
        id
        ls -al /
        ls -al /opt
        ls -al /opt/androidSdk
        ls -al /home
        ls -al /home/developer
        cat /etc/os-release'
      env:
        - ANDROID_ABI=armeabi-v7a
        - ANDROID_PLATFORM=android-26

    - <<: *android
      env:
        - ANDROID_ABI=arm64-v8a
        - ANDROID_PLATFORM=android-26
