language: generic
os: linux
dist: xenial

services:
  - docker

jobs:
  include:
    - &clang-11
      dist: bionic
      compiler: clang
      addons:
        apt:
          sources: &clang-11-sources
            - ubuntu-toolchain-r-test
            - sourceline: deb https://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main
              key_url: https://apt.llvm.org/llvm-snapshot.gpg.key
          packages: [ clang-11, g++-10 ]
      env:
        - CXX=clang++-11
        - CXXSTD="-std=c++20"

    - &android
      compiler: clang
      script: |
        docker run -it -v ${TRAVIS_BUILD_DIR}:/source bojoe/cpp-android-ndk-build-env-ubuntu:r22beta1 '
        cmake -H/source -B/home/developer/build -GNinja -DCMAKE_TOOLCHAIN_FILE=/opt/androidSdk/ndk/android-ndk-r22-beta1/build/cmake/android.toolchain.cmake -DANDROID_ABI=${ANDROID_ABI} -DANDROID_PLATFORM=${ANDROID_PLATFORM} -DCMAKE_BUILD_TYPE=Release -DPEGTL_BUILD_EXAMPLES=OFF
        cmake --build /home/developer/build --target all'
      env:
        - ANDROID_ABI=armeabi-v7a
        - ANDROID_PLATFORM=android-26

    - <<: *android
      env:
        - ANDROID_ABI=armeabi-v7a
        - ANDROID_PLATFORM=android-26

    - <<: *android
      env:
        - ANDROID_ABI=arm64-v8a
        - ANDROID_PLATFORM=android-26

    - dist: bionic
      compiler: clang
      addons:
        apt:
          sources: *clang-11-sources
          packages: [ clang-11, clang-tidy-11, g++-10 ]
      env:
        - CXX=clang++-11
        - CLANG_TIDY=clang-tidy-11
      script:
        - make -kj3 clang-tidy

    - dist: bionic
      compiler: gcc
      addons:
        apt:
          sources: [ ubuntu-toolchain-r-test ]
          packages: [ g++-10, valgrind ]
      env:
        - CXX=g++-10
        - SPECIAL=valgrind
      script:
        - make -kj3 valgrind

script:
  - $CXX --version
  - make -j3 build/src/test/pegtl/test_setup
  - build/src/test/pegtl/test_setup
  - make -kj3
