name: clang-tidy

on: [push, pull_request]

jobs:
  clang-tidy:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clang-tidy-10
      run: sudo apt-get update && sudo apt-get install -yq clang-tidy-10

    - name: clang-tidy
      run: find include/ src/ -name '*.[hc]pp' | xargs -I '{}' clang-tidy-10 --quiet '{}' -- --std=c++17 -Iinclude 2>&1
