name: clang-tidy

on: [push, pull_request]

jobs:
  clang-tidy:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install clang-tidy-10
      run: sudo apt-get update && sudo apt-get install -yq clang-tidy-10

    - name: clang-tidy
      run: |
        for i in $( find include/ src/ -name '*.[hc]pp'); do
          echo $i
          clang-tidy-10 --quiet $i -- --std=c++17 -Iinclude
        done
