name: Main CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        image:
          # List: https://github.com/conan-io/conan-docker-tools
          - gcc8
          - gcc9
          - gcc10
          - clang50
          - clang60
          - clang7
          - clang8
          - clang9
          - clang10
          - clang11
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    container:
      image: conanio/${{matrix.image}}
      options: --user root

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure

  linux-gcc-extra:
    strategy:
      fail-fast: false
      matrix:
        env:
          - CXXSTD="-std=c++20"
          - CPPFLAGS="-fno-rtti"
          - CPPFLAGS="-fsanitize=undefined -fuse-ld=gold"
          - CPPFLAGS="-fsanitize=address -fuse-ld=gold"
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    container:
      image: conanio/gcc10
      options: --user root

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure

  linux-clang-extra:
    strategy:
      fail-fast: false
      matrix:
        env:
          - CXXSTD="-std=c++20"
          - CPPFLAGS="-fms-extensions"
          - CPPFLAGS="-fno-rtti"
          - CPPFLAGS="-fsanitize=undefined"
          - CPPFLAGS="-fsanitize=address"
        build_type: [Debug, Release]

    runs-on: ubuntu-latest

    container:
      image: conanio/clang11
      options: --user root

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure

  macos:
    strategy:
      fail-fast: false
      matrix:
        xcode:
            - '11'
            - '12'
        build_type: [Debug, Release]

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: ${{matrix.xcode}}

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}}

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure

  # TODO: ClangCL vs native VC++
  windows:
    strategy:
      fail-fast: false
      matrix:
        build_type: [Debug, Release]

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: cmake -E make_directory build

    - name: Configure
      shell: bash
      working-directory: build/
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -G "Visual Studio 16 2019" -T ClangCL

    - name: Build
      working-directory: build/
      run: cmake --build . --config ${{matrix.build_type}}

    - name: Test
      working-directory: build/
      run: ctest -C ${{matrix.build_type}} --output-on-failure
