# Even when building with C++17 support, std::filesystem was not initially implemented
# in several common tool-chains, or it required additional build logic to enable it.
# This GitHub Action is supposed to test whether or not the fallback/configuration logic
# for that works in PEGTL.
name: std-filesystem-fallbacks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  job:
    name: ${{ matrix.os }}-fallback
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Run all of them once we start
      matrix:
        os:
          # These OSs have default tool-chains which don't support std::filesystem without
          # additional work in the CMake logic.
          - ubuntu-16.04
          - macos-10.15

    steps:
      - uses: actions/checkout@v2
      - uses: lukka/get-cmake@latest
      - uses: lukka/run-vcpkg@latest
        with:
          vcpkgArguments:
            - boost-filesystem
      - uses: lukka/run-cmake@latest
        with:
          useVcpkgToolchainFile: true
