# Even when building with C++17 support, std::filesystem was not initially implemented
# in several common tool-chains, or it required additional build logic to enable it.
# This GitHub Action is supposed to test whether or not the fallback/configuration logic
# for that works in PEGTL.
name: std-filesystem-fallbacks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  ubuntu-gcc:
    name: ${{ matrix.os }} with ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    strategy:
      # Run all of them once we start
      fail-fast: false
      matrix:
        os:
          - ubuntu-16.04
          - ubuntu-18.04
        cc:
          - gcc-7
          - gcc-8
        include:
          - cc: gcc-7
            cxx: g++-7
          - cc: gcc-8
            cxx: g++-8

    steps:
      - uses: actions/checkout@v2

      - name: Cache Boost
        uses: actions/cache@v2.1.3
        id: cache-boost-filesystem
        with:
          path: "~/boost"
          key: boost-filesystem-${{ matrix.os }}
      
      - name: Install Boost
        shell: bash
        env:
          CACHE_HIT: ${{steps.cache-boost-filesystem.outputs.cache-hit}}
        run: |
          if [[ "$CACHE_HIT" == 'true' ]]; then
            sudo cp --force --recursive ~/boost/* /
          else
            sudo apt-get update && sudo apt-get install -yq libboost-filesystem-dev
            mkdir -p ~/boost
            for dep in libboost-filesystem-dev; do
              dpkg -L $dep | while IFS= read -r f; do if test -f $f; then echo $f; fi; done | xargs cp --parents --target-directory ~/boost/
            done
          fi

      - name: Create Build Environment
        # Some projects don't allow in-source building, so create a separate build directory
        # We'll use this as our working directory for all subsequent commands
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Note the current convention is to use the -S and -B options here to specify source 
        # and build directories, but this is only available with CMake 3.13 and higher.  
        # The CMake binaries on the Github Actions machines are (as of this writing) 3.12
        run: cmake "$GITHUB_WORKSPACE"
        env:
          CC: ${{matrix.cc}}
          CXX: ${{matrix.cxx}}

      - name: Build the Project
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Execute the build.  You can specify a specific target with "--target <NAME>"
        run: cmake --build . -v

      - name: Run the Tests
        # Use a bash shell so we can use the same syntax for environment variable
        # access regardless of the host operating system
        shell: bash
        working-directory: ${{runner.workspace}}/build
        # Execute tests defined by the CMake configuration.  
        # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
        run: ctest
